// 대시보드 목록 조회
export const GET_DASHBOARDS = 'GET_DASHBOARDS';
export const GET_DASHBOARDS_SUCCESS = 'GET_DASHBOARDS_SUCCESS';
export const GET_DASHBOARDS_ERROR = 'GET_DASHBOARDS_ERROR';

// 신규 대시보드 등록
export const POST_DASHBOARD = 'POST_DASHBOARD';
export const POST_DASHBOARD_SUCCESS = 'POST_DASHBOARD_SUCCESS';
export const POST_DASHBOARD_ERROR = 'POST_DASHBOARD_ERROR';
