// 대시보드 목록 조회
export const GET_DASHBOARDS = 'GET_DASHBOARDS';
export const GET_DASHBOARDS_SUCCESS = 'GET_DASHBOARDS_SUCCESS';
export const GET_DASHBOARDS_ERROR = 'GET_DASHBOARDS_ERROR';

// 대시보드 조회
export const GET_DASHBOARD = 'GET_DASHBOARD';
export const GET_DASHBOARD_SUCCESS = 'GET_DASHBOARD_SUCCESS';
export const GET_DASHBOARD_ERROR = 'GET_DASHBOARD_ERROR';
