// 대시보드 목록 조회
export const GET_DASHBOARDS = 'GET_DASHBOARDS';
export const GET_DASHBOARDS_SUCCESS = 'GET_DASHBOARDS_SUCCESS';
export const GET_DASHBOARDS_ERROR = 'GET_DASHBOARDS_ERROR';

// 신규 대시보드 등록
export const POST_DASHBOARD = 'POST_DASHBOARD';
export const POST_DASHBOARD_SUCCESS = 'POST_DASHBOARD_SUCCESS';
export const POST_DASHBOARD_ERROR = 'POST_DASHBOARD_ERROR';

//  대시보드 삭제
export const DELETE_DASHBOARD = 'DELETE_DASHBOARD';
export const DELETE_DASHBOARD_SUCCESS = 'DELETE_DASHBOARD_SUCCESS';
export const DELETE_DASHBOARD_ERROR = 'DELETE_DASHBOARD_ERROR';

// 대시보드 수정
export const PUT_DASHBOARD = 'PUT_DASHBOARD';
export const PUT_DASHBOARD_SUCCESS = 'PUT_DASHBOARD_SUCCESS';
export const PUT_DASHBOARD_ERROR = 'PUT_DASHBOARD_ERROR';
